Repository finnishtransportagency/harja, pull requests merged in 2020-11, with the labels that each got.

#1986 VHAR-2905 laskun eräpäivän enemman validointia
  README.md
  src/clj/harja/kyselyt/urakat.sql
  src/clj/harja/palvelin/komponentit/http_palvelin.clj
  src/clj/harja/palvelin/palvelut/laskut.clj
  src/clj/harja/palvelin/palvelut/urakat.clj
  src/cljc/harja/domain/lasku.cljc
  src/cljc/harja/pvm.cljc
  src/cljs/harja/ui/pvm.cljs
  src/cljs/harja/views/urakka/kulut.cljs
  test/clj/harja/palvelin/komponentit/http_palvelin_test.clj
  test/clj/harja/palvelin/palvelut/laskut_test.clj
  test/clj/harja/pvm_test.clj
  test/clj/harja/testi.clj
  test/cljs/harja/views/urakka/kulut_test.cljs
  test/doo/harja/runner.cljs
  tietokanta/src/main/resources/db/migration/V1_846__.sql
  tietokanta/testidata/laskut.sql
Labels: WIP

#1984 VHAR-3039 Älä yhdistä työkoneseurannan viivageometrioita
  src/clj/harja/kyselyt/tilannekuva.sql
Labels: odottaa

#2001 VHAR-2905 Printta kunnolla kuukaudet joissa on kirjain "ä"
  src/cljc/harja/pvm.cljc
  src/cljs/harja/ui/pvm.cljs
  src/cljs/harja/views/urakka/kulut.cljs
  test/clj/harja/pvm_test.clj
Labels: bug

#1972 Vhar 1653 tr rapsa
  src/clj/harja/kyselyt/laskut.sql
  src/clj/harja/palvelin/raportointi/raportit.clj
  src/clj/harja/palvelin/raportointi/raportit/kulut_tehtavaryhmittain.clj
  src/cljc/harja/pvm.cljc
  src/cljs/harja/views/raportit.cljs
  test/clj/harja/palvelin/raportointi/kulut_tehtavaryhmittain_test.clj
Labels: WIP

#1997 VHAR-2958 Laskutusyhteenveto-mhu feilaa väärän tyypin takia
  src/cljc/harja/fmt.cljc
  test/clj/harja/fmt_test.clj
  test/clj/harja/oikea_http_palvelin_jarjestelma_fixture.clj
  test/clj/harja/palvelin/komponentit/http_palvelin_test.clj
  test/clj/harja/palvelin/raportointi/laskutusyhteenveto_mhu_raportti_syva_test.clj
Labels: bug

#2009 Ohjeet ja työkalut cypress paikalliseen ajamiseen
  .circleci/docker-harja-cypress/Dockerfile
  .gitignore
  README.md
  kaynnista_cypress.sh
  package.json
Labels: enhancement

#2005 VHAR-3233 Tee pohja POT2-ilmoituksen näkymälle
  cypress/integration/pot_lomake.js
  dev-resources/less/application/application.less
  dev-resources/less/livi_tyylit.less
  dev-resources/less/napit.less
  dev-resources/less/pages/materiaalikirjasto.less
  dev-resources/less/pages/paallystys_ja_paikkaus.less
  dev-resources/less/pages/pot2.less
  src/clj/harja/kyselyt/paallystys.clj
  src/clj/harja/kyselyt/paallystys.sql
  src/clj/harja/kyselyt/pot2.clj
  src/clj/harja/kyselyt/pot2.sql
  src/clj/harja/palvelin/palvelut/yllapitokohteet/pot2.clj
  src/cljc/harja/domain/pot2.cljc
  src/cljs/harja/tiedot/urakka/pot2/massat.cljs
  src/cljs/harja/tiedot/urakka/pot2/pot2_tiedot.cljs
  src/cljs/harja/tiedot/urakka/urakka.cljs
  src/cljs/harja/views/urakka/paallystysilmoitukset.cljs
  src/cljs/harja/views/urakka/pot1_lomake.cljs
  src/cljs/harja/views/urakka/pot2/massalistaus.cljs
  src/cljs/harja/views/urakka/pot2/pot2_lomake.cljs
  src/cljs/harja/views/urakka/pot_yhteinen.cljs
  test/clj/harja/palvelin/palvelut/yllapitokohteet/paallystys_test.clj
  test/clj/harja/palvelin/palvelut/yllapitokohteet_test.clj
  tietokanta/testidata.sql
  tietokanta/testidata/yllapito/paallystys.sql
  tietokanta/testidata/yllapito/pot2.sql
Labels: WIP
